### ISSUE TITLE
dor-rights-auth: fix location OR stanford at file level

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-rights-auth#18]
Note:  this may also be a bug at object level.

@jkeck surmises that the way the dor-rights-auth parse method populates the rules, it is using a file hash key that takes the *last* value only, so it overwrites the stanford permissions with location permissions when location is last in the rights xml

**Comment by LynnMcRae** [comment]
We have changed the spec so that an OR between access rights is expressed in one access block, using two different \<machine> blocks instead of two different \<access> blocks, that is:

```
<access type="read">
   <machine>
      <group>stanford</group>
   </machine>
   <machine>
      <location>spec</location>
   </machine>
</access>
```
instead of 
```
<access type="read">
   <machine>
      <group>stanford</group>
   </machine>
<access type="read">
</access>
   <machine>
      <location>spec</location>
   </machine>
</access>
```
This applies to \<file> qualified blocks as well...only one \<access> block instead of two that repeat the file name.

**Comment by ndushay** [comment]
whiteboard scrawlings realted to above

![img_1642](https://cloud.githubusercontent.com/assets/96775/16435256/8175f874-3d49-11e6-92f0-4899dc4d06f6.JPG)

**Comment by LynnMcRae** [comment]
Rights Metadata page updated on consul (https://consul.stanford.edu/display/chimera/Rights+metadata+--+the+rightsMetadata+datastream)

Stanford-OR-location test objects updated
   https://purl-test.stanford.edu/vs077pq2501  (object level)
   https://purl-test.stanford.edu/gm746xg1831  (file level)

**Comment by ndushay** [comment]
@LynnMcRae   could we get some examples and clarifying documentation on what should happen with multiple files getting the same permissions?   (A vs. B from your whiteboard)

**Comment by ndushay** [comment]
dor-rights-auth code already behaves per requirements Lynn states.   Really, it's a matter of testing the diff location restricted objects again and seeing if we are okay with them end-to-end.
