### ISSUE TITLE
Update 'ars' rights metadata location with new IP (was: 171.67.134.179, new: 171.67.132.138)

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/dor-rights-auth#26]

**Comment by blalbrit** [comment]
This ticket spawns two technical tasks:

- Add IP address and identifier information to the shared_configs repo, here:
https://github.com/sul-dlss/shared_configs/blob/sul-stacks-prod/config/settings/production.yml
- The new identifier value has to be hard coded into dor-services so that it will appear to a user as an option in the Argo pulldown menu, here:
https://github.com/sul-dlss/dor-services/blob/6f5b2a590c4189f6a5400446f18714ee73f62102/lib/dor/datastreams/rights_metadata_ds.rb#L54-L63

**Comment by LynnMcRae** [comment]
The definitions are already present in dor-services so the second checkbox requires no action.

**Comment by ndushay** [comment]
@blalbrit @LynnMcRae   I believe this ticket is completed.  close it if you agree.

(this particular IP change was made per the commit Chris references above;  rights_metadata_ds is appropriate for all these tickets: #26, #27, #28, #29 and #30.

**Comment by ndushay** [comment]
deployed the IP change to prod
