### ISSUE TITLE
Update 'ars' location to include the following IP addresses

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/dor-rights-auth#28]
The following IPs should be added to the 'ars' and 'music' rights metadata locations (https://consul.stanford.edu/display/chimera/Rights+Metadata+Locations):
171.66.238.54 (mangelet)
171.66.238.64, 171.66.209.130 (gwillard)

**Comment by ndushay** [comment]
sul-dlss/shared_configs#439 puts these changes in uat.  There is a branch sul-stacks-prod-ip-updates  ready after we get sign off of the changes in uat.

**Comment by ndushay** [comment]
deployed the change to prod
