### ISSUE TITLE
Create 'hoover' location

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/dor-rights-auth#30]
With the following IP addresses:
172.20.215.234
171.66.115.31 and .32 (Hoover)
171.66.114.42 (Hoover)
171.67.128.41 (EAL kiosk)

https://consul.stanford.edu/display/chimera/Rights+Metadata+Locations

**Comment by jmartin-sul** [comment]
@blalbrit, i think the tickets for this should go in dor-services and shared_configs.  the new rights code should go here:
https://github.com/sul-dlss/dor-services/blob/v5.25.0/lib/dor/datastreams/rights_metadata_ds.rb#L52-L65

and the associated IP addresses would go in the corresponding location section here:  https://github.com/sul-dlss/shared_configs/blob/sul-stacks-prod/config/settings/production.yml

the above advice assumes this ticket's "hoover" location is different from the "hoover library" location that's already there; if this is actually the same location, only the shared_configs update should be needed.  (inconveniently, if this is a new hoover location, "hoover library" already uses the generic `'loc:hoover'` string)

**Comment by blalbrit** [comment]
Thanks @jmartin-sul - I was following the instructions that @LynnMcRae created here: https://consul.stanford.edu/display/chimera/Rights+Metadata+Locations . My understanding was that the dev team would gen the two additional tickets that are technical tasks.

I can confirm that we are talking about the "hoover library" (ie. the `loc:hoover` string).

**Comment by jmartin-sul** [comment]
@blalbrit:  ah, got it, sorry, didn't realize that was the intended workflow, but makes sense.

**Comment by ndushay** [comment]
sul-dlss/shared_configs#439 puts these changes in uat.  There is a branch sul-stacks-prod-ip-updates  ready after we get sign off of the changes in uat.

**Comment by ndushay** [comment]
deployed the change to prod
