### ISSUE TITLE
cut gem release after dark and citation-only methods avail [blocked by #39]

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-rights-auth#40]
PreReqs:
- [x] #37 implement `dark?` method
- [x] #39 implement `citation_only?` method

we need a new gem release so virtual-merge code can access `dark?` and `citation_only?`

**Comment by jmartin-sul** [comment]
done:
* https://rubygems.org/gems/dor-rights-auth/versions/1.4.0
* https://github.com/sul-dlss/dor-rights-auth/releases/tag/v1.4.0
