### ISSUE TITLE
Implement Location AND Stanford Restrictions

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/dor-rights-auth#9]
Currently, we support restricting content to any Stanford community member (in any location) **OR** any user at a particular location.

To satisfy the location based requirements, we'll also need to support when content is restricted to only be viewable by Stanford community members at a particular location.

See #8 for example XML.

**Comment by ndushay** [comment]
Probably need a whiteboard conversation to figure out what to do in this situation (starting point:  express the use case when this is true)

**Comment by peetucket** [comment]
Scenario is: viewable by Stanford authed user at any location, or location restricted with no Stanford login requirement.

**Comment by peetucket** [comment]
i.e. to view you must be webauthed AND in a specific location

**Comment by peetucket** [comment]
Discussions between Hannah, curators and others in the library tell us there are no known use cases for this scenario currently, and that is unlikely Stanford Library would accept materials with this rights requirement.  Defer any implementation until the use case demands it.
